apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: telemetry
      defaultBucket: building_data
      tlsSkipVerify: true
    secureJsonData:
      token: telemetry-token-12345
    isDefault: true
